name: audio
dependencies:
  - python=2.7
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipywidgets
  - nltk
  - pip:
    - wish
    - audio.bitstream
    - audio.coders
    - audio.filters
    - audio.fourier
#    - audio.index
    - audio.lp
    - audio.psychoacoustics
    - audio.quantizers
    - audio.wave

