name: audio
channels:
  - conda-forge
dependencies:
  - python=2.7
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipywidgets
  - nltk
  - nltk_data
  - pip:
    - wish
    - audio.bitstream
    - audio.coders
    - audio.filters
    - audio.fourier
    - audio.index
    - audio.lp
    - audio.psychoacoustics
    - audio.quantizers
    - audio.wave

