name: audio
#channels:
#  - conda-forge # for nltk-data
dependencies:
  - python=2.7
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipywidgets
  - nltk
#  - nltk_data # too large (>400MB) and I only need TIMIT.
  - pip:
    - wish
    - audio.bitstream
    - audio.coders
    - audio.filters
    - audio.fourier
    - audio.index
    - audio.lp
    - audio.psychoacoustics
    - audio.quantizers
    - audio.wave

